### ISSUE TITLE
identical gene name (mostly ncRNAs) in the Gprofiler 

### ISSUE THREAD

**Issue by smangul1** [smangul1/UMI-Reducer#2]
multiple instances of the identical gene name (mostly ncRNAs) in the Gprofiler output, which is problematic for DESeq2 (right now the identical gene names have to be removed by hand which is laborious).

**Comment by svandriesche** [comment]
when we convert gene ids into gene names, 
collapse gene names with identical gene names

**Comment by smangul1** [comment]
gene names are not the same per chr. But there are gene names with the same name across chromosomes. 

awk -F "," '{print $1"-"$2}' * | sort | uniq -c | awk '{if ($1>1) print}'
     22 geneName-chr
