### ISSUE TITLE
remove the field in the stat file

### ISSUE THREAD

**Issue by svandriesche** [smangul1/UMI-Reducer#7]
[svandrie@login2 SJV085_S1_L001_R1_001_ATCG]$ head SJV085_S1_L001_R1_001_ATCG_PCRDuplicatesCollapsed.number_of_reads_stat 
sample,Number of mapped reads,Number of reads mapped to unique location (UNIQUE reads),Number of reads alligments after collapsing PCR dublicated (an aligment may include several copies of reads) ,Number of reads after collapsing PCR dublicated (each read is present once) 
/u/home/s/svandrie/nobackup-kmartin/SJV085redo2/Collapsed//SJV085_S1_L001_R1_001_ATCG/SJV085_S1_L001_R1_001_ATCG_PCRDuplicatesCollapsed,1770146,1314948,1179766,857545

REMOVE THIS ONE:
Number of reads alligments after collapsing PCR dublicated (an aligment may include several copies of reads)

**Comment by smangul1** [comment]
Done!
